// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydcvbhqdnqzhisqwhjpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkY3ZiaHFkbnF6aGlzcXdoanB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MDEyMDYsImV4cCI6MjA1NTM3NzIwNn0.8gGkx3hH7kHNnQ7yLqvwFIIhYtMjTtgyGby6oUsSq50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);